"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KonvaNodeEvent = void 0;
var KonvaNodeEvent;
(function (KonvaNodeEvent) {
    KonvaNodeEvent["pointerover"] = "pointerover";
    KonvaNodeEvent["pointerout"] = "pointerout";
    KonvaNodeEvent["pointermove"] = "pointermove";
    KonvaNodeEvent["pointerleave"] = "pointerleave";
    KonvaNodeEvent["pointerenter"] = "pointerenter";
    KonvaNodeEvent["pointerdown"] = "pointerdown";
    KonvaNodeEvent["pointerup"] = "pointerup";
    KonvaNodeEvent["wheel"] = "wheel";
    KonvaNodeEvent["contextmenu"] = "contextmenu";
    KonvaNodeEvent["click"] = "click";
    KonvaNodeEvent["dblclick"] = "dblclick";
    KonvaNodeEvent["dragstart"] = "dragstart";
    KonvaNodeEvent["dragmove"] = "dragmove";
    KonvaNodeEvent["dragend"] = "dragend";
})(KonvaNodeEvent = exports.KonvaNodeEvent || (exports.KonvaNodeEvent = {}));
